model_type: "xgboost" # or "neural_network" or "lightgbm"
learning_rate: 0.01
# NN specific
# batch_size: 256
# epochs: 10
# XGBoost/LightGBM specific
max_depth: 7
n_estimators: 100
feast_repo_path: "src/feature_repo"
mlflow_experiment_name: "RankingModel"
feature_list:
  - "user_features_view:about_embedding"
  - "user_features_view:headline_embedding"
  - "user_features_view:onboarding_category_ids"
  - "user_features_view:total_likes" # Example aggregated feature
  - "user_features_view:total_bookmarks" # Example aggregated feature
  - "post_features_view:description_embedding"
  - "post_features_view:category_id"
  - "post_features_view:media_type"
  - "post_features_view:creator_id"
  - "post_features_view:post_age_hours"
  - "post_features_view:likes_count" # Example engagement feature
  - "post_features_view:bookmarks_count" # Example engagement feature
# User-Post Interaction features (some might be computed on-the-fly)
# These are examples and might need adjustment based on actual feature view definitions
#  - "user_post_interaction_features_view:is_post_category_in_onboarding"
#  - "user_post_interaction_features_view:is_post_category_in_top_N_interacted"
#  - "user_post_interaction_features_view:user_interacted_with_creator"
#  - "user_post_interaction_features_view:cosine_similarity_user_post_embedding" # This will likely be computed on-the-fly
#  - "user_post_interaction_features_view:user_interaction_rate_in_post_category"

# Label definition
positive_interaction_types: ['like', 'bookmark'] # Define what constitutes a positive interaction

# Data paths (assuming these are available or generated by another process)
# These paths point to where raw interaction data is stored, which Feast might use or
# the data_utils script might use to identify positive/negative pairs before fetching features.
# For this example, we'll assume data_utils.py handles fetching these and then uses Feast.
interaction_data_paths:
  train: "artifacts/data/train/interactions.csv"
  validation: "artifacts/data/validation/interactions.csv"
  # test: "artifacts/data/test/interactions.csv" # If you have a separate test set for final evaluation

# Negative sampling strategy
negative_sampling_ratio: 4 # For each positive sample, generate 4 negative samples

# Seed for reproducibility
random_seed: 42