# Configuration for the Ranking Service

feast_repo_path: "src/feature_repo" # Relative path to the feature_store.yaml's parent directory

# MLflow model details for the Ranking Model
mlflow_ranking_model_uri: "mlruns/446405664678046264/ab52ad39d045461f8e2a8ba6da84dde1/artifacts/model" # Example URI, replace with your actual model URI
ranking_model_type: "xgboost" # Supported types: "xgboost", "lightgbm", "tensorflow". Ensure predictor.py supports it.

# List of all features (view_name:feature_name or just feature_name if computed on-the-fly and model expects that name)
# These features are used by the RankingServiceTransformer:
# 1. To fetch from Feast (if "view_name:feature_name" format).
# 2. To define the columns and their order for the DataFrame passed to the ranking model.
# The model must have been trained on features with these exact names and in this order.
ranking_feature_list:
  # User features
  - "user_profile_features:about_embedding" # Example: Embedding of user's 'about' text
  - "user_profile_features:onboarding_category_ids" # Example: List of category IDs from user onboarding
  - "user_aggregated_stats:num_posts_created" # Was avg_posts_per_day

  # Post features
  - "post_details_features:description_embedding" # Example: Embedding of post's description
  - "post_details_features:category_id" # Example: Category ID of the post
  - "post_aggregated_derived_stats:num_likes_on_post" # Was num_likes_last_7_days
  - "post_aggregated_derived_stats:post_age_hours" # Was post_age_days

  # User-Post Interaction features (can be from Feast if precomputed, or computed on-the-fly)
  # If computed on-the-fly in RankingServiceTransformer._compute_on_the_fly_features,
  # then list the final feature name here as the model expects it.
  # Example:
  # - "user_post_interaction_features_view:cosine_similarity_user_post_embedding" # If from Feast
  - "is_post_category_in_onboarding" # Example of an on-the-fly feature (ensure transformer.py computes this)
  # - "user_post_ctr_last_30_days" # Example

  # Add all other features the ranking model was trained on.
  # Ensure the order matches the training order if your model is sensitive to it (most are).

# Column names used for creating the entity DataFrame for Feast
# and for accessing user_id and post_ids from the request in the transformer.
user_id_col_name: "user_id"
post_id_col_name: "post_id"