embedding_dim: 64
learning_rate: 0.001
batch_size: 512
epochs: 2
feast_repo_path: "src/feature_repo" # Relative to project root
mlflow_experiment_name: "TwoTowerRecommender"
user_tower_features:
  - "user_profile_features:about_embedding"
  - "user_profile_features:headline_embedding"
  # ... other features
post_tower_features:
  - "post_details_features:description_embedding"
  - "post_details_features:category_id"
  - "post_details_features:media_type"
  - "post_details_features:creator_id"
  # ... other features